### ISSUE TITLE
ghaerdi roadmap

### ISSUE THREAD

**Issue by ghaerdi** [ghaerdi/ghaerdi#78]
### Features and bugs.
- [ ] Add dev.to url.
- [ ] Fix index page or replace it.
- [ ] Fix typing animation

### Maybe
- [] Remove instagram
- [] Move social btn to the left, vertical.
- [] Change btn to navigate.
